### ISSUE TITLE
ERROR - 'NoneType' object has no attribute 'create_dagrun'

### ISSUE THREAD

**Issue by ZeeD** [mastak/airflow_multi_dagrun#11]
I was trying to run some examples and I stumbled in this error

I'm running the master version of your code with apache-airflow 1.10.6 and python 3.7.5

```
*** Reading local file: /home/vito.detullio/airflow/logs/trigger_with_multi_dagrun_sensor/gen_target_dag_run/2019-12-10T00:00:00+00:00/1.log
[2019-12-11 17:19:03,862] {taskinstance.py:630} INFO - Dependencies all met for <TaskInstance: trigger_with_multi_dagrun_sensor.gen_target_dag_run 2019-12-10T00:00:00+00:00 [queued]>
[2019-12-11 17:19:03,876] {taskinstance.py:630} INFO - Dependencies all met for <TaskInstance: trigger_with_multi_dagrun_sensor.gen_target_dag_run 2019-12-10T00:00:00+00:00 [queued]>
[2019-12-11 17:19:03,876] {taskinstance.py:841} INFO - 
--------------------------------------------------------------------------------
[2019-12-11 17:19:03,876] {taskinstance.py:842} INFO - Starting attempt 1 of 1
[2019-12-11 17:19:03,876] {taskinstance.py:843} INFO - 
--------------------------------------------------------------------------------
[2019-12-11 17:19:03,894] {taskinstance.py:862} INFO - Executing <Task(TriggerMultiDagRunOperator): gen_target_dag_run> on 2019-12-10T00:00:00+00:00
[2019-12-11 17:19:03,894] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'trigger_with_multi_dagrun_sensor', 'gen_target_dag_run', '2019-12-10T00:00:00+00:00', '--job_id', '419', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/trigger_with_multi_dagrun_sensor.py', '--cfg_path', '/tmp/tmp6vren6xo']
[2019-12-11 17:19:06,320] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run [2019-12-11 17:19:06,320] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-12-11 17:19:06,321] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run [2019-12-11 17:19:06,320] {dagbag.py:92} INFO - Filling up the DagBag from /home/vito.detullio/airflow/dags/trigger_with_multi_dagrun_sensor.py
[2019-12-11 17:19:06,346] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run [2019-12-11 17:19:06,346] {cli.py:545} INFO - Running <TaskInstance: trigger_with_multi_dagrun_sensor.gen_target_dag_run 2019-12-10T00:00:00+00:00 [running]> on host FGVIL021718L
[2019-12-11 17:19:06,361] {logging_mixin.py:112} INFO - [2019-12-11 17:19:06,361] {dagbag.py:92} INFO - Filling up the DagBag from /home/vito.detullio/airflow/dags
[2019-12-11 17:19:06,460] {taskinstance.py:1058} ERROR - 'NoneType' object has no attribute 'create_dagrun'
Traceback (most recent call last):
  File "/home/vito.detullio/airflow-venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 930, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/vito.detullio/airflow/plugins/multi_dagrun/operators/multi_dagrun.py", line 43, in execute
    dr = trigger_dag.create_dagrun(
AttributeError: 'NoneType' object has no attribute 'create_dagrun'
[2019-12-11 17:19:06,488] {taskinstance.py:1089} INFO - Marking task as FAILED.
[2019-12-11 17:19:06,552] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run Traceback (most recent call last):
[2019-12-11 17:19:06,552] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run   File "/home/vito.detullio/airflow-venv/bin/airflow", line 37, in <module>
[2019-12-11 17:19:06,552] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run     args.func(args)
[2019-12-11 17:19:06,553] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run   File "/home/vito.detullio/airflow-venv/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-12-11 17:19:06,553] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run     return f(*args, **kwargs)
[2019-12-11 17:19:06,553] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run   File "/home/vito.detullio/airflow-venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 551, in run
[2019-12-11 17:19:06,553] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run     _run(args, dag, ti)
[2019-12-11 17:19:06,553] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run   File "/home/vito.detullio/airflow-venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 469, in _run
[2019-12-11 17:19:06,553] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run     pool=args.pool,
[2019-12-11 17:19:06,553] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run   File "/home/vito.detullio/airflow-venv/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-12-11 17:19:06,553] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run     return func(*args, **kwargs)
[2019-12-11 17:19:06,553] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run   File "/home/vito.detullio/airflow-venv/lib/python3.7/site-packages/airflow/sentry.py", line 144, in wrapper
[2019-12-11 17:19:06,553] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run     return func(task_instance, *args, session=session, **kwargs)
[2019-12-11 17:19:06,553] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run   File "/home/vito.detullio/airflow-venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 930, in _run_raw_task
[2019-12-11 17:19:06,553] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run     result = task_copy.execute(context=context)
[2019-12-11 17:19:06,553] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run   File "/home/vito.detullio/airflow/plugins/multi_dagrun/operators/multi_dagrun.py", line 43, in execute
[2019-12-11 17:19:06,554] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run     dr = trigger_dag.create_dagrun(
[2019-12-11 17:19:06,554] {base_task_runner.py:115} INFO - Job 419: Subtask gen_target_dag_run AttributeError: 'NoneType' object has no attribute 'create_dagrun'
[2019-12-11 17:19:08,872] {logging_mixin.py:112} INFO - [2019-12-11 17:19:08,871] {local_task_job.py:124} WARNING - Time since last heartbeat(0.02 s) < heartrate(5.0 s), sleeping for 4.979225 s
[2019-12-11 17:19:13,855] {logging_mixin.py:112} INFO - [2019-12-11 17:19:13,854] {local_task_job.py:103} INFO - Task exited with return code 1

```

**Comment by ZeeD** [comment]
sorry, I forgot to add the "common_target" DAG to airflow
